version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: votacao
      POSTGRES_PASSWORD: votacao
      POSTGRES_DB: votacao
    ports:
      - "5432:5432"